In [10]:
"""입력 토큰 인덱스를 임베딩 벡터로 변환하는 클래스.

    주어진 단어 집합 크기(vocab_size)과 임베딩 차원(d_model)을 바탕으로 임베딩 레이어를 생성.
    입력 토큰을 처리할 때 사용.

"""

import torch
import torch.nn as nn
class Embeddings(nn.Module):
    '''입력 토큰과 출력 토큰을 d_model 차원의 벡터로 변환하는 임베딩 레이어.

    Attributes:
        embedding(nn.Embedding): 임베딩 레이어로, 단어 집합 크기(vocab_size)와 임베딩 차원(d_model)을 인자로 받음.
        d_model(int): 임베딩 벡터의 차원
    '''
    def __init__(self, vocab_size, d_model):
        super(Embeddings, self).__init__()
        """Embeddings 클래스의 생성자
        
        Args:
            vocab_size(int): 단어 집합 크기, 즉, vocab 사이즈
            d_model(int): 임베딩 벡터의 차원
        """
        self.embedding = nn.Embedding(num_embeddings = vocab_size, embedding_dim = d_model) 
        self.d_model = d_model

    def forward(self, x):
        """입력 토큰 인덱스를 임베딩 벡터로 변환하고 스케일링.

        Args:
            x(torch.Tensor): 입력 텐서로, 토큰의 정수형 인덱스 포함. (배치 크기, 시퀀스 길이)

        Returns:
            torch.Tensor: d_model 차원의 임베딩 벡터를 반환. (배치 크기, 시퀀스 길이, 임베딩 차원)
        """
        return self.embedding(x) * math.sqrt(self.d_model) #attention mechanism의 안정성을 위해 스케일링

In [12]:
# nn.Embedding의 예시
sentence = "This is embedding example."
word_set = set(sentence.split())
print(word_set)

vocab = {token: i+1 for i, token in enumerate(word_set)}
print(vocab)

embedding_layer = nn.Embedding(num_embeddings=len(vocab), embedding_dim=3)

embedding_layer.weight, embedding_layer.weight[0]

{'example.', 'This', 'is', 'embedding'}
{'example.': 1, 'This': 2, 'is': 3, 'embedding': 4}


(Parameter containing:
 tensor([[ 0.9610, -0.8996, -0.8464],
         [-0.2177,  1.2763, -0.1698],
         [ 0.9773,  0.2740,  0.9070],
         [-0.8541,  0.2068, -2.0466]], requires_grad=True),
 tensor([ 0.9610, -0.8996, -0.8464], grad_fn=<SelectBackward0>))

In [14]:
import torch
import torch.nn as nn

vocab_size = 10  
d_model = 6 

embedding = nn.Embedding(vocab_size, d_model)

x = torch.tensor([[1, 2, 3], [4, 5, 6]])  # (배치 크기 2, 시퀀스 길이 3)

x_embedding = embedding(x)

print(x_embedding.shape)  # 결과: (배치 크기, 시퀀스 길이, 임베딩 차원)
print(x_embedding)

torch.Size([2, 3, 6])
tensor([[[-0.4557,  0.0910,  0.3981, -0.0495, -1.2533, -0.3818],
         [ 0.0997,  0.3162, -0.2746,  0.1792, -0.5500,  0.0124],
         [-0.7752,  0.2090,  0.5267,  0.0403, -3.5858, -0.7578]],

        [[ 2.0962, -1.0729,  0.2327,  0.7603,  2.0336, -0.9209],
         [ 0.2261,  0.7553, -0.0878, -0.0246,  0.4555,  1.0830],
         [-1.0600,  1.0272, -0.5820, -0.3202, -0.1183,  0.3251]]],
       grad_fn=<EmbeddingBackward0>)
